name: Build and push docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  docker:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Release
        uses: krzwro/automated-release-action@v0.2.1
        id: release

      - name: Build and push to registry
        uses: docker/build-push-action@v3
        if: ${{ steps.release.outputs.version }}
        with:
          context: .
          push: true
          tags: ${{ inputs.image_name }}:${{ steps.release.outputs.version }}
          build-args: RELEASED_VERSION=${{ steps.release.outputs.version }}
